version: '3'

services:
  glee:
    build:
      context: .
      dockerfile_inline: |
        FROM asyncapi/cli
        USER root
        RUN apk add --no-cache --virtual .gyp python3 make g++ && \
            rm -rf /var/lib/apt/lists/* && \
            asyncapi new glee && \
            cd project && \
            npm install
        ENTRYPOINT 
    ports:
      - "8080:3210"
    volumes:
      - ${PWD}/asyncapi.yaml:/app/asyncapi.yaml
      - ${PWD}/output:/app 
    networks:
      - default
    user: root
    entrypoint: []
    working_dir: /app/project
    command: npm run dev

    
networks:
  default: {}