import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import sonarjs from 'eslint-plugin-sonarjs';
import security from 'eslint-plugin-security';
import github from 'eslint-plugin-github';

export default [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  sonarjs.configs.recommended,
  security.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js'],
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      sonarjs,
      security,
      github,
    },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        process: 'readonly',
        console: 'readonly',
        module: 'readonly',
        require: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        exports: 'readonly',
        global: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
      },
    },
    rules: {
      strict: 0,
      'github/array-foreach': 'error',
      'eol-last': ['error', 'always'],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      'sonarjs/no-small-switch': 'off',
      'security/detect-non-literal-fs-filename': 'off',
      'no-process-exit': 'error',
      'no-warning-comments': 'error',
      'no-loop-func': 'error',
      curly: ['error'],
      'no-multi-spaces': 'error',
      'consistent-return': 'off',
      'consistent-this': ['off', 'self'],
      'func-style': 'off',
      'max-nested-callbacks': ['error', 3],
      camelcase: 'off',
      'no-debugger': 'warn',
      'no-empty': 'warn',
      'no-invalid-regexp': 'warn',
      'no-unused-expressions': 'warn',
      'no-fallthrough': 'warn',
      'sonarjs/cognitive-complexity': 'warn',
      eqeqeq: 'error',
      'no-undef': 'off',
      'no-dupe-keys': 'error',
      'no-empty-character-class': 'error',
      'no-self-compare': 'error',
      'valid-typeof': 'error',
      'no-unused-vars': 'off',
      'handle-callback-err': 'error',
      'no-shadow-restricted-names': 'error',
      'no-new-require': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'block-scoped-var': 'error',
      'no-else-return': 'error',
      'no-throw-literal': 'error',
      'no-void': 'error',
      radix: 'error',
      'wrap-iife': ['error', 'outside'],
      'no-shadow': 'off',
      'no-path-concat': 'error',
      'valid-jsdoc': [
        'off',
        {
          requireReturn: false,
          requireParamDescription: false,
          requireReturnDescription: false,
        },
      ],
      'no-spaced-func': 'error',
      'semi-spacing': 'error',
      quotes: ['error', 'single'],
      'key-spacing': [
        'error',
        {
          beforeColon: false,
          afterColon: true,
        },
      ],
      indent: ['error', 2],
      'no-lonely-if': 'error',
      'no-floating-decimal': 'error',
      'brace-style': [
        'error',
        '1tbs',
        {
          allowSingleLine: true,
        },
      ],
      'comma-style': ['error', 'last'],
      'no-multiple-empty-lines': [
        'error',
        {
          max: 1,
        },
      ],
      'no-nested-ternary': 'error',
      'operator-assignment': ['error', 'always'],
      'padded-blocks': ['error', 'never'],
      'quote-props': ['error', 'as-needed'],
      'keyword-spacing': [
        'error',
        {
          before: true,
          after: true,
          overrides: {},
        },
      ],
      'space-before-blocks': ['error', 'always'],
      'array-bracket-spacing': ['error', 'never'],
      'computed-property-spacing': ['error', 'never'],
      'space-in-parens': ['error', 'never'],
      'space-unary-ops': [
        'error',
        {
          words: true,
          nonwords: false,
        },
      ],
      'wrap-regex': 'error',
      'linebreak-style': 'off',
      semi: ['error', 'always'],
      'arrow-spacing': [
        'error',
        {
          before: true,
          after: true,
        },
      ],
      'no-class-assign': 'error',
      'no-const-assign': 'error',
      'no-this-before-super': 'error',
      'no-var': 'error',
      'object-shorthand': ['error', 'always'],
      'prefer-arrow-callback': 'error',
      'prefer-const': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      '@typescript-eslint/no-unused-vars': 'error',
    },
  },
  {
    files: ['**/*.spec.ts', '**/*.spec.tsx', 'src/help/command.ts', '**/*.test.ts'],
    rules: {
      'no-undef': 'off',
      'security/detect-non-literal-fs-filename': 'off',
      'sonarjs/no-duplicate-string': 'off',
      'security/detect-object-injection': 'off',
      'max-nested-callbacks': 'off',
      'sonarjs/no-identical-functions': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'no-use-before-define': 'off',
      'sonarjs/cognitive-complexity': 'off',
    },
  },
  {
    files: ['src/apps/cli/internal/base.ts'],
    rules: {
      '@typescript-eslint/ban-ts-comment': 'off',
    },
  },
  {
    files: ['**/*.js'],
    rules: {
      '@typescript-eslint/no-var-requires': 'off',
    },
  },
];
