name: 'Generator for AsyncAPI documents'
description: 'Use this action to generate docs or code from your AsyncAPI document. Use default templates or provide your custom ones.'
inputs:
  template: 
    description: 'Template for the generator. Official templates are listed here https://github.com/search?q=topic%3Aasyncapi+topic%3Agenerator+topic%3Atemplate. You can pass template as npm package, url to git repository, link to tar file or local template.'
    default: '@asyncapi/markdown-template@0.10.0'
    required: false
  filepath: 
    description: 'Location of the AsyncAPI document.'
    default: 'asyncapi.yml'
    required: false
  parameters: 
    description: 'The template that you use might support and even require specific parameters to be passed to the template for the generation.'
    required: false
  output:
    description: 'Directory where to put the generated files.'
    required: false
    default: 'output'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'file-text'
  color: purple
